### ISSUE TITLE
About the paired dataset

### ISSUE THREAD

**Issue by sjchasel** [ddz16/MoMu#1]
I downloaded the data from https://pan.baidu.com/s/1aHJoYTTZWDHPCcRuu9I7Fg. But there is only a folder called "process" that contains text data. I can't find the corresponding molecular graph.

**Comment by ddz16** [comment]
Sorry, that was a mistake. Now all the corresponding molecular graphs can be found in：https://pan.baidu.com/s/1FfsyS42CP9IZ3RZpWeaBVw. The passward is 1234.
