### ISSUE TITLE
Molecular Graph conversion

### ISSUE THREAD

**Issue by Teedos** [ddz16/MoMu#2]
Hi,
First of all thank you for your work! I noticed that your Molecular Graphs are stored as pyg Data objects. Would it be possible to convert them to a format that is accessible to rdkit? 
I tried using https://github.com/ddz16/MoleculePrediction/blob/9d4047fe6f9b0ed8a6ed5fba1fa12b17455554d3/loader.py#L102
and pyg's to_smiles, but neither of the two worked.
Is it possible that you provide the original molecule graph/ SMILES files (not pyg data format)?
Thank you.

**Comment by ddz16** [comment]
We will provide a new link for all the types of datasets today afternoon. (including smiles, graphs, texts)

**Comment by ddz16** [comment]
link: https://pan.baidu.com/s/1hYbVOMhr7pwLkUtl5FWqbg 
password: 1234
